#!/bin/bash

source $(dirname $0)/../util/print.sh
source $(dirname $0)/../util/commit_length.sh

source $(dirname $0)/../asset/icon.sh

source $(dirname $0)/../style/color.sh

validate_commit_length

PATTERN="([a-z:]) ([a-z]+)(\(.*\))?: ([a-z])$"

if ! [[ "$MESSAGE" =~ $PATTERN ]]; then
  print_error "Commit message did not match 'icon type(scope): subject'"
fi

exit 1